version: "3.9"
services:
  redis:
    image: redis:7-alpine
    container_name: novelist_redis
    restart: unless-stopped
    ports:
      - "6379:6379"

  celery_worker:
    image: python:3.12-slim
    command: >
      bash -c "
        pip install celery redis &&
        pip install -r /code/requirements.txt &&
        celery -A core.celery_app.celery_app worker --loglevel=info"
    volumes:
      - .:/code
    depends_on:
      - redis
